theme: jekyll-theme-minimal
title: Future Skribisto Web Help
description: This is a brief overview of the Skribisto writing software interface.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Start Here
    url: Start Here
  - title: Skribisto Interface
    url: Skribisto Interface
  - title: Main Menu
    url: Main Menu
  - title: Starting a New Project
    url: Starting a New Project
  - title: Deselecting a Menu Panel
    url: Deselecting a Menu Panel
  - title: Settings Menu
    url: Settings Menu

