theme: jekyll-theme-minimal
title: Future Skribisto Web Help
description: A simple template based on minimal jekyll theme, https://kut.ai/gh-pages-template/setup
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Start Here
    url: Start Here
  - title: Skribisto Interface
    url: skribisto interface
