theme: jekyll-theme-minimal
title: Future Skribisto Web Help
description: This is a brief overview of the Skribisto writing software interface.  
The main site is: https://github.com/jacquetc/skribisto  
This is a simple template based on minimal jekyll theme, found here https://kut.ai/gh-pages-template/setup
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Start Here
    url: Start Here
  - title: Skribisto Interface
    url: Skribisto Interface
  - title: Main Menu
    url: Main Menu
